### ISSUE TITLE
Notice: Undefined index: label in RulesUICategory::getOptions() 

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/rules#81] opened 2021-05-08 22:17 UTC
Visiting the page admin/config/workflow/rules/components/add (among others) puts several versions of "Notice: Undefined index: label in RulesUICategory::getOptions()" in the watchdog log.

Specifically:

1. Visit the page admin/config/workflow/rules/components/add
2. Click "Continue".
3. Check the watchdog log at admin/reports/dblog to see the notices.

Debugging reveals that this occurs because the data for `'taxonomy_vocabulary'` returned by `rules_rules_core_data_info()` is lacking its `'label'` field.

PR to follow.

**Comment by indigoxela** [comment] 2021-05-09 08:20
@bugfolder many thanks for providing a PR. That notice annoyed me several times, I also identified the root cause and wanted to provide a PR, but you beat me to it. :smile:  Yes, it's the missing label.

I can confirm that your PR fixes it. And additionally the "Taxonomy Vocabulary" label now properly shows up in the dropdown - that option item used to be empty before.

Here's a screenshot:

![vocab-label](https://user-images.githubusercontent.com/842066/117565114-f6b8be80-b0af-11eb-8264-9c1282c011f4.png)

Works for me :+1:

**Comment by laryn** [comment] 2021-10-29 23:12
Thanks for reporting and submitting a PR @bugfolder, and for testing @indigoxela. Merged.

**Closed as completed** 2021-10-29 23:12 UTC
