### ISSUE TITLE
Unable to update site: Unresolved dependency Entity tokens (Version = 2.0.0 required)

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/rules#178] opened 2022-03-22 19:55 UTC
When attempting to update all out of date modules on a site, the update fails due to an increase in dependency version:

> Error
> Unresolved dependency
> Entity tokens (Version = 2.0.0 required) less
> Rules requires this module and version. Currently using Entity tokens version
1.1.0-beta

I think this may be related: https://github.com/backdrop-contrib/rules/issues/176

**Comment by argiepiano** [comment] 2022-03-22 20:25
@jenlampton the latest version of Rules depends en version 2 of Entity Tokens. You still have version 1. Please update to the current version of entity Tokens - 2.0.1

**Comment by jenlampton** [comment] 2022-03-22 23:56
The error happened during the update. 

I think maybe I can't do both the updates together. Entity Tokens needs to be updated first? This seems like a big problem. Is there a core issue to address this?

**Comment by argiepiano** [comment] 2022-03-23 00:02
That sounds serious. This may happen because of the major version change in ET. Perhaps Backdrop is set  to stay within the major version, instead of updating to version 2.

**Comment by argiepiano** [comment] 2022-03-23 01:02
I can confirm that Backdrop doesn't consider version 2 of a module to be an update of the latest version 1. Is this a bug? Worth opening an issue in the backdrop queue.

**Comment by jenlampton** [comment] 2022-03-23 03:22
> Is this a bug?

It sounds like it. If the module releases are tagged `1.x-1.0.0` and then `1.x-2.0.0` it should certainly identify that 2 is the version after 1. If there was a `-dev` or `-beta` involved in either release name, that might cause some confusion, but either way it should be addressed in core.

**Comment by argiepiano** [comment] 2022-05-28 14:06
As this (versions issue) seems to be a core problem and there is an issue for that, we can close this now. 

The solution that was implemented in this specific use case is to mark version 1 of ET as unsupported.

**Closed as completed by argiepiano** 2022-05-28 14:06 UTC
