### ISSUE TITLE
`rules_config_load_multiple()` should load entities by `name`, not `id`, and should return a correct array

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/rules#117] opened 2022-01-08 21:03 UTC
Since the $names function parameter clearly indicates that names (not numeric IDs) are provided to this function, there are two problems:

1. You should use `entity_load_multiple_by_name` instead of `entity_load_multiple`, AND
2. You should return an array keyed by the names (the rules_config names). At the moment the returned array is not keyed (i.e. it is a sequential array, not an associative array, and uses sequential keys 1, 2, 3, etc) 

In fact, another issue: the return variable is built with `$entity->$property`, and $property is never defined.  This undefined variable is throwing a Notice whenever you create a rule.   I expect this may be creating issues in the tests as well.

In fact there is actually no need to build the `$ret` return variable, since `entity_load_multiple_by_name`  provides exactly what you need to return.

**Comment by argiepiano** [comment] 2022-01-08 21:11
I see another issue with this function:  
```php
  if (!isset($info['entity keys']['name'])) {
    return $entities;
  }
```

This is exactly the opposite of what you want. You want to return $entities keyed by `name` if the entity configuration defines a `name` column. BTW, this is the case with `rules_config` entities, so there is really no need to do this check anyway.

**Comment by argiepiano** [comment] 2022-01-08 21:15
And   `module_load_include('inc', 'rules', 'includes/entity.functions');` is really not needed at all.

**Comment by argiepiano** [comment] 2022-01-08 21:17
PR #118

**Comment by argiepiano** [comment] 2022-01-08 21:25
I just looked at this function in version 2.1.5 (the latest release) and it looks much better, similar to my PR. I'm wondering what prompted the changes to the dev version? 

One crucial, missing part in the 2.1.5 release version of this function is:

```php  
  if (empty($names)) {
    $names = FALSE;
  }
```

This code is there in the dev version (but there are the other issues I mentioned above). If you don't do this `$names = FALSE` assignment, this function will return an empty array when you do `rules_config_load_multiple()` without parameters, instead of returning all rules_config in the system

**Comment by laryn** [comment] 2022-01-08 21:55
> I'm wondering what prompted the changes to the dev version?

I have no doubt I messed it up while trying to merge in and clean up years worth of D7 updates. Sorry (and thanks!).

**Comment by bugfolder** [comment] 2022-01-12 16:56
Duplicate of https://github.com/backdrop-contrib/rules/issues/110 (current PR adjusted to point to that issue).

**Closed as completed by bugfolder** 2022-01-12 16:56 UTC
